---
- hosts: all

  vars:
    swift_seed_url_1404: "https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a/swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a-ubuntu14.04.tar.gz"
    swift_seed_url_1510: "https://swift.org/builds/development/ubuntu1510/swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a/swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a-ubuntu15.10.tar.gz"

  tasks:
  
    - include: base.yml
    - include: swift.yml
    - include: libdispatch.yml
